db-uri = "postgres://authenticator:testpw@127.0.0.1:5432/restore_drill"
db-schemas = "fabula"
db-anon-role = "anon"
jwt-secret = "test-secret-test-secret-test-secret-0123456789"
server-port = 3000
db-pool = 5
